### PR TITLE
钉钉报警二次开发

### PR DESCRIPTION
**Pull request by hezhiqiang8909**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [x] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**The description of the PR:**

**Other information:**

### CODE REVIEW

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by hezhiqiang8909** [comment]
image

**Comment by xuxueli** [comment]
你好，这个分支与master分支差异化较大，建议单独维护分支，分支版本可以维护在这个issue里：https://github.com/xuxueli/xxl-job/issues/154

**Pull request closed without merging**
